name: GDB with python3 support

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  arm:
    runs-on: ubuntu-latest
    name: devkitARM
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: devkitPro/binutils-gdb
          ref: devkitARM-gdb
          path: build-gdb
      - name: Install required packages
        run: |
          make git-core cmake python3-dev build-essential wget \
          bison flex libncurses5-dev libreadline-dev texinfo pkg-config \
          python3-pip python3-setuptools libglib2.0-dev libc6-dbg \
          autotools-dev automake autoconf liblz4-dev libelf-dev \
          libtinfo5 \
          libgmp-dev libmpfr-dev libmpc-dev mesa-common-dev libfreeimage-dev \
          zlib1g-dev libusb-dev libudev-dev libexpat1-dev \
          xz-utils bzip2
      - run: cp ./.binutils-gdb/arm-release.sh ./build-gdb/
      - run: cd build-gdb && chmod +x arm-release.sh && ./arm-release.sh -g gdb
      - uses: softprops/action-gh-release@v0.1.14
        with:
          files: gdb-*.tar.gz
          name: devkitARM GDB with Python3 support


  a64:
    runs-on: ubuntu-latest
    name: devkitA64

    container: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v3
        with:
          repository: devkitPro/binutils-gdb
          ref: devkitA64
          path: build-gdb
      - name: Install required packages
        run: |
          make git-core cmake python3-dev build-essential wget \
          bison flex libncurses5-dev libreadline-dev texinfo pkg-config \
          python3-pip python3-setuptools libglib2.0-dev libc6-dbg \
          autotools-dev automake autoconf liblz4-dev libelf-dev \
          libtinfo5 \
          libgmp-dev libmpfr-dev libmpc-dev mesa-common-dev libfreeimage-dev \
          zlib1g-dev libusb-dev libudev-dev libexpat1-dev \
          xz-utils bzip2
      - run: cp ./.binutils-gdb/a64-release.sh ./build-gdb/
      - run: cd build-gdb && chmod +x a64-release.sh && ./a64-release.sh -g gdb
      - uses: softprops/action-gh-release@v0.1.14
        with:
          files: gdb-*.tar.gz
          name: devkitA64 GDB with Python3 support
